name: deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm ci --ignore-scripts --no-audit
      - name: Test
        run: npm test
  build:
    needs: [test]
    runs-on: ubuntu-latest
    env:
      IMAGE: aussidavid/thelinkedpeople-monday.com-integration
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Install
        run: npm ci --ignore-scripts --no-audit
      - name: Test
        run: npm test
      - name: Build
        run: docker build . --file Dockerfile --cache-from $IMAGE:latest --tag $IMAGE:latest
      - name: Push
        run: docker push $IMAGE:latest
